### ISSUE TITLE
Missing pod resource in kotary-role ?

### ISSUE THREAD

**Issue by herveleclerc** [ca-gip/kotary#2]
Hello, 
I have this error in korary pod

1 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube-system:kotary" cannot list resource "pods" in API group "" at the cluster scope

fixed by addin "pods" in ClusterRole kotary-role 

```
- apiGroups: [ "" ]
    resources: [ "namespaces", "nodes", "configmaps", "pods" ]
```

**Comment by clementblaise** [comment]
Hello @herveleclerc sorry for the delay, thank you for pointing it out I have update the example deployment
